### ISSUE TITLE
UnboundLocalError: local variable 'affinity_matrix' referenced before assignment

### ISSUE THREAD

**Issue by wangji9** [ustbjdl1021/improved-snl-unet#1]

**Comment by wangji9** [comment]
def getAtt(self, x):
        t = self.transform_t(x)
        p = self.transform_p(x)
        b, c, h, w = t.size()
        t = t.view(b, c, -1).permute(0, 2, 1)
        p = p.view(b, c, -1)
        m = torch.bmm(torch.relu(t), torch.relu(p))
        m += m.permute(0, 2, 1)
        m_hat = m / 2
        degree = torch.sum(m_hat, dim=2)
        degree[degree != 0] = torch.sqrt(1.0 / degree[degree != 0])
        affinity_matrix *= degree.unsqueeze(1)
        affinity_matrix *= degree.unsqueeze(2)
        
        return affinity_matrix

**Comment by yht183** [comment]
Sorry we submitted the wrong old version of the file, the error has been updated

**Comment by ustbjdl1021** [comment]
> ```
> def getAtt(self, x):
>     t = self.transform_t(x)
>     p = self.transform_p(x)
>     b, c, h, w = t.size()
>     t = t.view(b, c, -1).permute(0, 2, 1)
>     p = p.view(b, c, -1)
>     m = torch.bmm(torch.relu(t), torch.relu(p))
>     m += m.permute(0, 2, 1)
>     m_hat = m / 2
>     degree = torch.sum(m_hat, dim=2)
>     degree[degree != 0] = torch.sqrt(1.0 / degree[degree != 0])
>     affinity_matrix *= degree.unsqueeze(1)
>     affinity_matrix *= degree.unsqueeze(2)
>     
>     return affinity_matrix
> ```

Sorry we submitted the wrong old version of the file, the error has been updated
